#!/usr/bin/env node
// =============================================================================
// build-i18n-jp.mts — Merge all JP locale domain files into a single standalone
// file for runtime lazy-loading (~69KB source → ~25KB minified).
// =============================================================================
// The JP locale is NOT bundled into the main IIFE (saving ~69KB from the
// initial payload). Instead, it's loaded on-demand when the user switches
// to Japanese via toggleFormLanguage().
//
// Output: assets/jp-locale.js (loaded via fetch + eval at runtime)
// =============================================================================

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, basename } from 'node:path';

const ROOT = process.cwd();
const JP_DIR = resolve(ROOT, 'i18n/locales/jp');
const OUT_DIR = resolve(ROOT, 'assets');

// Domain files in order (matches i18n/locales/jp/index.js imports)
const DOMAINS = [
  'loader',
  'a11y',
  'header',
  'form',
  'public',
  'status',
  'table',
  'landing',
  'siswa',
  'ui',
  'candidate',
  'admin',
  'button',
  'footer',
  'alert',
];

// Read and merge all JP domain files
const merged: Record<string, any> = {};

for (const domain of DOMAINS) {
  const filePath = resolve(JP_DIR, `${domain}.js`);
  if (!existsSync(filePath)) {
    console.error(`[build-i18n-jp] Missing: ${domain}.js`);
    process.exit(1);
  }

  const content = readFileSync(filePath, 'utf8');

  // Extract the exported const name and its value
  // Pattern: export const <name> = { ... };
  const match = content.match(/export\s+const\s+(\w+)\s*=\s*(\{[\s\S]*\});?\s*$/);
  if (match) {
    // Evaluate the object literal safely
    try {
      const obj = new Function(`return ${match[2]}`)();
      Object.assign(merged, obj);
    } catch (e) {
      console.error(`[build-i18n-jp] Failed to parse ${domain}.js:`, e);
      process.exit(1);
    }
  }
}

// Generate standalone JS file that exposes jp locale data
const outPath = resolve(OUT_DIR, 'jp-locale.js');
const output = `// jp-locale.js — Standalone JP locale bundle for lazy-loading.
// Generated by scripts/build-i18n-jp.mts — DO NOT EDIT MANUALLY.
// Loaded at runtime via fetch() when user switches to Japanese.
window.__ASJ_JP_LOCALE__ = ${JSON.stringify(merged, null, 0)};
`;

writeFileSync(outPath, output, 'utf8');
const size = (Buffer.byteLength(output) / 1024).toFixed(1);
console.log(`[build-i18n-jp] → assets/jp-locale.js (${size} KB, ${DOMAINS.length} domains merged)`);
